### ISSUE TITLE
The default node packages are outdated and contains security issues

### ISSUE THREAD

**Issue by sio4** [gobuffalo/cli#26]
(branched from https://github.com/gobuffalo/buffalo/issues/2144#issuecomment-913290051)

Moving the discussion in the above issue here since the original issue was about https://github.com/gobuffalo/docs and the following issue is of https://github.com/gobuffalo/cli.

> Now I'm at:
> <...>
> It's a python issue and it appears you need python2 and I have python 3. There has to be a better way :( I hate python, it truly sucks.
> 
> Oh well, not sure this project is maintained anymore. So many deprecated dependencies.

@tresero, "Now" means when you were trying to run `buffalo new books` right? Yeah, indeed, currently it has some deprecated dependencies in the `packages.json` mostly in `devDependencies` section, and also they have some sub dependencies containing security issues.

Recently, I was working on this issue for my old project using buffalo and I think my humble temporary patch (against a vanilla project) may work for you too. You can find the patch from https://gist.github.com/sio4/61687c81c318582948017bd43a8aabe8

In this patch, I updated `node-sass` from "~4.13.1" to "~6.0.1" along with some other packages, and it has worked well so far.

>> FYI, buffalo cli (the package be installed by the command) was introduced recently and the command buffalo is now not a part of this repo anymore.
> 
> Not sure what you mean. So the docs are completely wrong. I'm not sure what to do at this point. It looked promising, but...

What I mean is that previously the package "buffalo" provided the `buffalo` command but now the command has its own dedicated project named "cli" under the "buffalo eco-system". The repository is here, and the release note about this change is there: https://github.com/gobuffalo/buffalo/releases/tag/v0.17.0

This is a very new change that happened this month, and I would say "the docs need to be updated accordingly" instead of "completely wrong". One of them is my PR for adding 'v'. :-)

So...

### Description

The default npm packages configured by `buffalo new` in `packages.json` are outdated and contains security issues.

* node-sass compilation error (needs python2)
* security issue on tar (added by copy-webpack-plugin, fixed at 4.4.18)
* security issue on glob-parent (added by copy-webpack-plugin, fixed at 5.1.2)
* security issue on trim-newlines (added by node-sass indirectly via meow, fixed at 3.0.1)

### Steps to Reproduce the Problem

  0. make sure you don't have python2 installed
  1. Install a recent version of buffalo (0.17.x)
  2. run `buffalo new coke` --> will end with compilation error (node-sass)
  3. check security issues on the installed node packages.

### Expected Behavior

New and *clean* app skeleton without compilation errors.

### Actual Behavior

Compilation errors and old/deprecated packages with security issues were configured/installed.

### Info

This issue is related to https://github.com/gobuffalo/buffalo/issues/2100 and https://github.com/gobuffalo/buffalo/issues/2144

<details>

```
-> Go: Checking installation
✓ The `go` executable was found on your system at: /opt/google/go/bin/go

-> Go: Checking minimum version requirements
✓ Your version of Go, 1.16.7, meets the minimum requirements.

-> Go: Checking Package Management
✓ You are using Go Modules (`go`) for package management.

-> Go: Checking PATH
✓ Your PATH contains /home/sio4/go/bin.

-> Node: Checking installation
✓ The `node` executable was found on your system at: /home/sio4/.nvm/versions/node/v14.17.6/bin/node

-> Node: Checking minimum version requirements
✓ Your version of Node, v14.17.6, meets the minimum requirements.

-> NPM: Checking installation
✓ The `npm` executable was found on your system at: /home/sio4/.nvm/versions/node/v14.17.6/bin/npm

-> NPM: Checking minimum version requirements
✓ Your version of NPM, 6.14.15, meets the minimum requirements.

-> Yarn: Checking installation
✓ The `yarnpkg` executable was found on your system at: /home/sio4/.nvm/versions/node/v14.17.6/bin/yarnpkg

-> Yarn: Checking minimum version requirements
✓ Your version of Yarn, 1.22.11, meets the minimum requirements.

-> PostgreSQL: Checking installation
✘ The `postgres` executable could not be found on your system.
For help setting up your Postgres environment please follow the instructions for you platform at:

https://www.postgresql.org/download/

-> MySQL: Checking installation
✓ The `mysql` executable was found on your system at: /usr/bin/mysql

-> MySQL: Checking minimum version requirements
✓ Your version of MySQL, 8.0.26, meets the minimum requirements.

-> SQLite3: Checking installation
✓ The `sqlite3` executable was found on your system at: /usr/bin/sqlite3

-> SQLite3: Checking minimum version requirements
✓ Your version of SQLite3, 3.31.1, meets the minimum requirements.

-> Cockroach: Checking installation
✘ The `cockroach` executable could not be found on your system.
For help setting up your Cockroach environment please follow the instructions for you platform at:

https://www.cockroachlabs.com/docs/stable/

-> Buffalo (CLI): Checking installation
✓ The `buffalo` executable was found on your system at: /home/sio4/go/bin/buffalo

-> Buffalo (CLI): Checking minimum version requirements
✓ Your version of Buffalo (CLI), v0.17.2, meets the minimum requirements.

-> Buffalo: Application Details
Pwd         /home/sio4/git/cook
Root        /home/sio4/git/cook
GoPath      /home/sio4/go
PackagePkg  cook
ActionsPkg  cook/actions
ModelsPkg   cook/models
GriftsPkg   cook/grifts
WithModules true
Name        cook
Bin         bin/cook
VCS         git
WithPop     true
WithSQLite  false
WithDep     false
WithWebpack true
WithNodeJs  true
WithYarn    true
WithDocker  true
WithGrifts  true
AsWeb       true
AsAPI       false
InApp       true
PackageJSON {map[build:webpack --mode production --progress dev:webpack --watch]}

-> Buffalo: config/buffalo-app.toml
name = "cook"
bin = "bin/cook"
vcs = "git"
with_pop = true
with_sqlite = false
with_dep = false
with_webpack = true
with_nodejs = true
with_yarn = true
with_docker = true
with_grifts = true
as_web = true
as_api = false

-> Buffalo: config/buffalo-plugins.toml
[[plugin]]
  binary = "buffalo-pop"
  go_get = "github.com/gobuffalo/buffalo-pop/v2"

-> Buffalo: go.mod
module cook

go 1.16

require github.com/gobuffalo/buffalo-pop/v2 v2.3.0 // indirect
```

</details>

**Comment by tresero** [comment]
Yes you are correct. 

I'm not really a Go programmer since I just started this, but I have 40+ years programming databases (oracle/PG), and C/C++, PHP, etc. I don't think I can be much help here :(

**Comment by sio4** [comment]
More information about the security issues:

https://github.com/advisories/GHSA-5955-9wpr-37jh (tar)
https://github.com/advisories/GHSA-ww39-953v-wcq6 (glob-parent)
https://github.com/advisories/GHSA-7p7h-4mm5-852v (trim-newlines)

**Comment by sio4** [comment]
> I'm not really a Go programmer since I just started this, but I have 40+ years programming databases (oracle/PG), and C/C++, PHP, etc. I don't think I can be much help here :(

I think reporting issues here with 40+ years of experience itself is very helpful for the team and fans of buffalo like me. If you can provide the result of my patch It could be more helpful. The test steps could be:

1. once facing the issue, apply the patch by running `patch -p1 buffalo-webpack.patch` in the app directory.
2. run `yarn`

My expectation is that no more compilation errors and some dependency warnings are gone.

I checked it on my laptop and it looks good, but not fully sure for now.

**Comment by sio4** [comment]
Note: the temporary patch for testing (https://gist.github.com/sio4/61687c81c318582948017bd43a8aabe8) also contains the results of PR #25

**Comment by tresero** [comment]
Seems to work, some notes

Updated your patch command in case someone is not familiar with diff/patch.

`patch -p1 < buffalo-webpack.patch`

After your patch, you need to run
`go get your_app/actions`

It seems that the buffalo server doesn't really work on 0.0.0.0 though. I can only see anything on localhost. The ADDR when set to 0.0.0.0 only sets tcp6 and that's it.
`
tcp6       0      0 :::3030                 :::*                    LISTEN
`

Again, I'm probably doing something wrong, but I'm not sure what.

**Comment by sio4** [comment]
Oh, my mistake on the command line. Thanks for correction.

By the way, not sure about `go get` part. I guess `go mod tidy` was not executed while you run `buffalo new` if you faced module related issue. (I am afk and cannot test now)

For the listening address part, you can check the following code. Localhost is used for dev mode while 0.0.0.0 is the default for prod.

https://github.com/gobuffalo/buffalo/blob/20f545e952c31f65eadf7a4833388ed2eaa37589/options.go#L90

Anyway, thanks for your confirmation!

**Comment by sio4** [comment]
fixed by #27. closing.

**Comment by tresero** [comment]
I can't really work on my linux server so I moved to my windows 10 box. Some notes.

gnu patch isn't really working, but I copied the files from my patched linux version.

When running yarn the following warnings are sent.
yarn install v1.22.11
info No lockfile found.
[1/4] Resolving packages...
warning popper.js@1.16.1: You can find the new Popper v2 at @popperjs/core, this package is dedicated to the legacy v1
warning @babel/cli > @nicolo-ribaudo/chokidar-2 > braces > snapdragon > source-map-resolve > resolve-url@0.2.1: https://github.com/lydell/resolve-url#deprecated
warning @babel/cli > @nicolo-ribaudo/chokidar-2 > braces > snapdragon > source-map-resolve > urix@0.1.0: Please see https://github.com/lydell/urix#deprecated
warning node-sass > request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
warning node-sass > node-gyp > request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
warning node-sass > request > har-validator@5.1.5: this library is no longer supported
warning node-sass > request > uuid@3.4.0: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
[2/4] Fetching packages...
info fsevents@2.3.2: The platform "win32" is incompatible with this module.
info "fsevents@2.3.2" is an optional dependency and failed compatibility check. Excluding it from installation.
[3/4] Linking dependencies...
[4/4] Building fresh packages...
success Saved lockfile.
Done in 17.38s.


I'm about to test on windows and will let you know.

**Comment by sio4** [comment]
Not sure what was the issue in the Linux box. My laptop is also Linux (Ubuntu 20) and buffalo works well on it.

By the way, the PR (#27) for this issue was merged into `main` branch (which is extended from the patch) so I guess you may be able to use the new HEAD (not yet released). The PR also upgraded `popper.js` and `node-sass` to recent versions and fixed those warnings of deprecation. However, I couldn't find updates for `babel` so the warnings of them are still existing but they will not affect the production codes.

Otherwise, I think the output is pretty good.
